# .travis.yaml
language: generic
before_install:
    - pyenv versions
    - pyenv shell 3.7
    - pip3 install --upgrade pip
after_success:
    - pwd
before_deploy:
    # install PyGithub
    - pip3 install PyGithub
    # download githubrelease.py
    - wget https://raw.githubusercontent.com/Immueggpain/citools/master/githubrelease.py
deploy:
    provider: script
    script: python3 githubrelease.py "eat_auto_sell-$TRAVIS_TAG.zip"
    skip_cleanup: true
    on:
        tags: true
